import Foundation

public struct ConfigurationFile: Identifiable, Sendable {
    public var id: String { url.path }
    public let title: String
    public let url: URL
    public let editable: Bool
    public let readOnlyReason: String
    public init(title: String, url: URL, editable: Bool = true, readOnlyReason: String = "Generated from service settings. Use the service's settings to change these values.") { self.title = title; self.url = url.resolvingSymlinksInPath(); self.editable = editable; self.readOnlyReason = readOnlyReason }
}
public struct ConfigurationAccess: Sendable {
    public let store: StateStore
    public let runner: any CommandRunning
    public init(store: StateStore = StateStore(), runner: any CommandRunning = CommandRunner()) { self.store = store; self.runner = runner }
    public func files(_ runtime: RuntimeInstallation) throws -> [ConfigurationFile] {
        if runtime.engine == .php {
            let output = try runner.run(runtime.executable, ["--ini"], environment: [:]).checked()
            var paths: [ConfigurationFile] = []
            for line in output.components(separatedBy: .newlines) {
                if line.hasPrefix("Loaded Configuration File:"), let value = line.split(separator: ":", maxSplits: 1).last {
                    let path = value.trimmingCharacters(in: .whitespaces)
                    if path.hasPrefix("/"), FileManager.default.fileExists(atPath: path) { paths.append(ConfigurationFile(title: "php.ini", url: URL(fileURLWithPath: path))) }
                }
                if line.hasPrefix("Scan for additional .ini files in:"), let value = line.split(separator: ":", maxSplits: 1).last {
                    let path = value.trimmingCharacters(in: .whitespaces)
                    if path.hasPrefix("/") {
                        for file in (try? FileManager.default.contentsOfDirectory(at: URL(fileURLWithPath: path), includingPropertiesForKeys: nil)) ?? [] where file.pathExtension == "ini" {
                            paths.append(ConfigurationFile(title: file.lastPathComponent, url: file))
                        }
                    }
                }
            }
            if let pool = SiteManager(store: store, runner: runner).runtimeConfigurationURL(runtime), FileManager.default.fileExists(atPath: pool.path) {
                paths.append(ConfigurationFile(title: "Morrow PHP-FPM pool", url: pool, editable: false, readOnlyReason: "Generated by Sites. Choose PHP and project settings in Sites to change its managed pool."))
            }
            return paths.sorted { $0.title < $1.title }
        }
        if runtime.engine == .node && runtime.source == "nvm" {
            let url = NodeVersionManager(store: store, runner: runner).directory.appendingPathComponent("alias/default")
            return FileManager.default.fileExists(atPath: url.path) ? [ConfigurationFile(title: "nvm default alias", url: url, editable: false, readOnlyReason: "Managed by nvm. Select a Node version in Runtimes to change the default.")] : []
        }
        return []
    }
    public func database(_ instance: DatabaseInstance) -> [ConfigurationFile] {
        [ConfigurationFile(title: "Managed server configuration", url: store.configURL(instance), editable: false)]
    }
    public func save(_ file: ConfigurationFile, text: String, original: String) throws {
        guard file.editable else { throw MorrowError.message("This file is generated from the service settings. Edit those settings instead.") }
        let current = try String(contentsOf: file.url, encoding: .utf8)
        guard current == original else { throw MorrowError.message("The file changed outside Morrow. Reload it before saving.") }
        let permissions = try FileManager.default.attributesOfItem(atPath: file.url.path)[.posixPermissions]
        try text.write(to: file.url, atomically: true, encoding: .utf8)
        if let permissions { try FileManager.default.setAttributes([.posixPermissions: permissions], ofItemAtPath: file.url.path) }
    }
}
